/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.VistaVentanaPpal;
import javax.swing.JDialog;
import vistaGestor.LoginDialogGestor;
import vistaMozo.LoginDialogMozo;

/**
 *
 * @author simonlg
 */
public class InicioAppJDialog extends javax.swing.JDialog implements VistaVentanaPpal {

    /**
     * Creates new form InicioAppJDialog
     */
    public InicioAppJDialog() {
        setVisible(true);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMozo = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        btnMozo.setText("MOZO");
        btnMozo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMozoActionPerformed(evt);
            }
        });
        getContentPane().add(btnMozo);
        btnMozo.setBounds(50, 90, 120, 90);

        jButton2.setText("GESTOR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(220, 90, 120, 90);

        setBounds(0, 0, 416, 339);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMozoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMozoActionPerformed
        iniciarInterfaceMozo();
    }//GEN-LAST:event_btnMozoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        iniciarInterfaceGestor();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMozo;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void iniciarInterfaceMozo() {
        dispose();
        JDialog l = new LoginDialogMozo();
        l.setVisible(true);
    }

    @Override
    public void iniciarInterfaceGestor() {
        dispose();
        JDialog l = new LoginDialogGestor();
        l.setVisible(true);
    }
}
