/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.VistaVentanaPpal;
import controlador.ControladorVentanaPrincipal;
import javax.swing.JDialog;

/**
 *
 * @author simonlg
 */
public class VentantaPrincipalJFrame extends javax.swing.JFrame implements VistaVentanaPpal {

    /**
     * Creates new form VentantaPrincipalJFrame
     */
    private ControladorVentanaPrincipal controlador;
    
    public VentantaPrincipalJFrame() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Bienvenido al Sistema de Atencion del Restaurante");
        controlador = new ControladorVentanaPrincipal(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMozo = new javax.swing.JButton();
        btnGestor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btnMozo.setText("MOZO");
        btnMozo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMozoActionPerformed(evt);
            }
        });
        getContentPane().add(btnMozo);
        btnMozo.setBounds(60, 90, 110, 80);

        btnGestor.setText("GESTOR");
        btnGestor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestorActionPerformed(evt);
            }
        });
        getContentPane().add(btnGestor);
        btnGestor.setBounds(220, 90, 110, 80);

        setBounds(0, 0, 416, 339);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMozoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMozoActionPerformed
        // TODO add your handling code here:
        iniciarInterfaceMozo();
    }//GEN-LAST:event_btnMozoActionPerformed

    private void btnGestorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestorActionPerformed
        // TODO add your handling code here:
        iniciarInterfaceGestor();
    }//GEN-LAST:event_btnGestorActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGestor;
    private javax.swing.JButton btnMozo;
    // End of variables declaration//GEN-END:variables

    @Override
    public void iniciarInterfaceMozo() {
        JDialog l = new LoginDialogMozo(this, rootPaneCheckingEnabled);
        l.setVisible(true);
      
    }

    @Override
    public void iniciarInterfaceGestor() {
        JDialog l = new LoginDialogGestor(this, rootPaneCheckingEnabled);
        l.setVisible(true);
    }
}
