/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistaGestor;

import controlador.ControladorGestor;
import controlador.VistaGestor;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import modelo.Gestor;
import modelo.UnidadProcesadora;

/**
 *
 * @author simonlg
 */
public class SeleccionUP_JDialog extends javax.swing.JDialog implements VistaGestor {

    ControladorGestor controlador;

    /**
     * Creates new form SeleccionUP_JDialog
     */
    public SeleccionUP_JDialog(Gestor gestor) {
        setModal(true);
        initComponents();
        setLocationRelativeTo(null);
        controlador = new ControladorGestor(this, gestor);
        mostrarUnidadesProcesadoras();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listUnidadesP = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Seleccione la UP:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 30, 160, 60);

        btnAceptar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAceptar.setText("ACEPTAR");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAceptar);
        btnAceptar.setBounds(40, 120, 120, 40);

        jScrollPane1.setViewportView(listUnidadesP);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(210, 30, 100, 140);

        setBounds(0, 0, 359, 248);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        ingresarPuesto();
    }//GEN-LAST:event_btnAceptarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList listUnidadesP;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mostrarUnidadesProcesadoras() {
        listUnidadesP.setListData(controlador.getFachada().getUnidadesProcesadoras().toArray());
    }

    @Override
    public void ingresarPuesto() {
        
        UnidadProcesadora up = (UnidadProcesadora) listUnidadesP.getSelectedValue();
        this.controlador.entrarUP(up);
        JFrame f = new JFrame();
        f.setSize(800, 400);
        PanelInicioGestor pi = new PanelInicioGestor(controlador);
        f.setTitle("Bienvenido " + controlador.getGestor().getNombreCompleto());
        f.setContentPane(pi);
        dispose();
        f.setVisible(true);
    }

    @Override
    public void mostrarPedidosPendientes() {
        
    }

    @Override
    public void tomarPedido() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void finalizarPedido() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void error(String mensaje) {
         JOptionPane.showMessageDialog(this, mensaje, "Error en aplicacion gestor", JOptionPane.ERROR_MESSAGE);
    }
}
