/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistaMozo;

import controlador.ControladorLoginMozo;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import modelo.Item;
import modelo.Mesa;

/**
 *
 * @author simonlg
 */
public class InfoMesaPanel extends JPanel {

    private ActionListener al;
    private ControladorLoginMozo controlador;//se podria quitar, ya que los botones de este los escucha el panel estatico???

    public void setEscuchador(ActionListener al) {
        this.al = al;
        btnAgregarArt.addActionListener(al);
        btnCerrarMesa.addActionListener(al);
        btnTransferirMesa.addActionListener(al);
    }

    DefaultTableModel modelo;

    public InfoMesaPanel() {
        initComponents();
        modelo = new DefaultTableModel();
        modelo.addColumn("Artículo");
        modelo.addColumn("Cantidad");
        modelo.addColumn("Precio");
        modelo.addColumn("Subtotal");
        modelo.addColumn("Estado");
        modelo.addColumn("Gestor");
        this.tableItemsConsumidos.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableItemsConsumidos = new javax.swing.JTable();
        btnTransferirMesa = new javax.swing.JButton();
        txtTotal = new javax.swing.JLabel();
        btnAgregarArt = new javax.swing.JButton();
        btnCerrarMesa = new javax.swing.JButton();

        setLayout(null);

        tableItemsConsumidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tableItemsConsumidos);

        add(jScrollPane1);
        jScrollPane1.setBounds(10, 10, 650, 130);

        btnTransferirMesa.setText("TRANSFERIR MESA");
        btnTransferirMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransferirMesaActionPerformed(evt);
            }
        });
        add(btnTransferirMesa);
        btnTransferirMesa.setBounds(280, 150, 180, 50);

        txtTotal.setText("Total:");
        add(txtTotal);
        txtTotal.setBounds(180, 150, 100, 40);

        btnAgregarArt.setText("AGREGAR ITEM");
        btnAgregarArt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarArtActionPerformed(evt);
            }
        });
        add(btnAgregarArt);
        btnAgregarArt.setBounds(10, 150, 160, 40);

        btnCerrarMesa.setText("CERRAR MESA");
        btnCerrarMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarMesaActionPerformed(evt);
            }
        });
        add(btnCerrarMesa);
        btnCerrarMesa.setBounds(470, 150, 190, 50);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTransferirMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransferirMesaActionPerformed

    }//GEN-LAST:event_btnTransferirMesaActionPerformed

    private void btnCerrarMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarMesaActionPerformed

    }//GEN-LAST:event_btnCerrarMesaActionPerformed

    private void btnAgregarArtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarArtActionPerformed

    }//GEN-LAST:event_btnAgregarArtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarArt;
    private javax.swing.JButton btnCerrarMesa;
    private javax.swing.JButton btnTransferirMesa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableItemsConsumidos;
    private javax.swing.JLabel txtTotal;
    // End of variables declaration//GEN-END:variables

    public void mostrarServicios(Mesa seleccionada) {
        limpiarTabla();
        String[] datos = new String[6];
        double total = 0;

        ArrayList<Item> listaItems = seleccionada.getServicio().getItems();
            for (Item i : listaItems) {
                datos[0] = i.getArt().getNombre();
                datos[1] = i.getCantidad() + "";
                datos[2] = i.getArt().getPrecio() + "";
                datos[3] = (i.getCantidad()) * (i.getArt().getPrecio()) + "";
                datos[4] = i.getPedido().getEstado().toString();
                i.
                datos[5] = " -- FALTA IMPLEMENTAR --";  //modelo.addColumn("Gestor");  
                ////////////////////////Para poder hacer estos vamos a tener que hacer esto desde la Up cuando el pedido este agregado ahi
                modelo.addRow(datos);

                total += (double) (i.getCantidad()) * (i.getArt().getPrecio());
            }

        txtTotal.setText("Total: " + total);
    }

    public void limpiarTabla() {
        int cantFilas = tableItemsConsumidos.getRowCount();
        for (int i = cantFilas - 1; i >= 0; i--) {
            modelo.removeRow(i);
        }
    }

}
