/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistaMozo;

import controlador.ControladorLoginMozo;
import java.awt.event.ActionListener;
import javax.swing.JPanel;

/**
 *
 * @author simonlg
 */
public class InfoMesaPanel extends JPanel{

    private ActionListener al;
    private ControladorLoginMozo controlador;
    
    public void setEscuchador(ActionListener al) {
        this.al = al;
        btnAgregarArt.addActionListener(al);
        btnCerrarMesa.addActionListener(al);
        btnTransferirMesa.addActionListener(al);
    }

    public InfoMesaPanel() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableItemsConsumidos = new javax.swing.JTable();
        btnTransferirMesa = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnAgregarArt = new javax.swing.JButton();
        btnCerrarMesa = new javax.swing.JButton();
        lblTotalServicio = new javax.swing.JLabel();

        setLayout(null);

        tableItemsConsumidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nombre artículo", "Cantidad", "$ unitario", "Sub-total", "Estado", "Gestor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableItemsConsumidos);

        add(jScrollPane1);
        jScrollPane1.setBounds(10, 10, 560, 150);

        btnTransferirMesa.setText("TRANSFERIR MESA");
        btnTransferirMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransferirMesaActionPerformed(evt);
            }
        });
        add(btnTransferirMesa);
        btnTransferirMesa.setBounds(70, 240, 180, 50);

        jLabel2.setText("Total:");
        add(jLabel2);
        jLabel2.setBounds(380, 180, 40, 40);

        btnAgregarArt.setText("AGREGAR ITEM");
        btnAgregarArt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarArtActionPerformed(evt);
            }
        });
        add(btnAgregarArt);
        btnAgregarArt.setBounds(130, 180, 160, 40);

        btnCerrarMesa.setText("CERRAR MESA");
        btnCerrarMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarMesaActionPerformed(evt);
            }
        });
        add(btnCerrarMesa);
        btnCerrarMesa.setBounds(340, 240, 190, 50);
        add(lblTotalServicio);
        lblTotalServicio.setBounds(440, 180, 80, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTransferirMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransferirMesaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTransferirMesaActionPerformed

    private void btnCerrarMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarMesaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarMesaActionPerformed

    private void btnAgregarArtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarArtActionPerformed

    }//GEN-LAST:event_btnAgregarArtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarArt;
    private javax.swing.JButton btnCerrarMesa;
    private javax.swing.JButton btnTransferirMesa;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotalServicio;
    private javax.swing.JTable tableItemsConsumidos;
    // End of variables declaration//GEN-END:variables



}
