/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistaMozo;

import controlador.VistaServicioMesa;
import modelo.Mesa;

/**
 *
 * @author Dominique
 */
public class ServicioMesa extends javax.swing.JFrame implements VistaServicioMesa{

    private Mesa mesa;
    /**
     * Creates new form ServicioMesa
     */
    public ServicioMesa(Mesa me) {
        initComponents();       
        setLocationRelativeTo(null);
        setVisible(true);
        
        
        //////////////// Mandar a la tabla la lista de los items consumidos por la mesa
        
        
        
    }

  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableItemsConsumidos = new javax.swing.JTable();
        btnTransferirMesa = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnAgregarArt = new javax.swing.JButton();
        btnCerrarMesa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Items consumidos:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 160, 50);

        tableItemsConsumidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nombre artículo", "Cantidad", "$ unitario", "Sub-total", "Estado", "Gestor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableItemsConsumidos);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 50, 560, 260);

        btnTransferirMesa.setText("TRANSFERIR Mesa");
        getContentPane().add(btnTransferirMesa);
        btnTransferirMesa.setBounds(90, 390, 180, 50);

        jLabel2.setText("Total:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(390, 334, 160, 40);

        btnAgregarArt.setText("Agregar artículo");
        btnAgregarArt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarArtActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregarArt);
        btnAgregarArt.setBounds(10, 320, 160, 40);

        btnCerrarMesa.setText("CERRAR Mesa");
        getContentPane().add(btnCerrarMesa);
        btnCerrarMesa.setBounds(290, 390, 190, 50);

        setBounds(0, 0, 596, 500);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarArtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarArtActionPerformed
        // TODO add your handling code here:
        agregarItem();
    }//GEN-LAST:event_btnAgregarArtActionPerformed

   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarArt;
    private javax.swing.JButton btnCerrarMesa;
    private javax.swing.JButton btnTransferirMesa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableItemsConsumidos;
    // End of variables declaration//GEN-END:variables

    @Override
    public void agregarItem() {
        new AgregarItemJDialog(this, rootPaneCheckingEnabled).setVisible(true);
    }
}
