/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistaMozo;

import controlador.ControladorMozo;
import controlador.VistaMozo;
import modelo.Mesa;
import modelo.Mozo;

/**
 *
 * @author Dominique
 */
public class TransferenciaOkJDialog extends javax.swing.JDialog {

    private ControladorMozo controlador;
    private VistaMozo vista;

    /**
     * Creates new form TransferenciaOkJDialog
     */
    public TransferenciaOkJDialog(ControladorMozo pControlador) {
        initComponents();
        setModal(true);
        setLocationRelativeTo(null);
        controlador = pControlador;
        cargarDatosTransferencia();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAceptar = new javax.swing.JButton();
        btnRechazar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMozoOrigen = new javax.swing.JLabel();
        txtMesaNro = new javax.swing.JLabel();
        txtMesaEstado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAceptar);
        btnAceptar.setBounds(30, 220, 160, 60);

        btnRechazar.setText("Rechazar");
        btnRechazar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRechazarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRechazar);
        btnRechazar.setBounds(220, 220, 150, 60);

        jLabel1.setText("SOLICITUD DE TRANSFERENCIA");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 10, 220, 40);

        jLabel2.setText("Solicitud del mozo:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 70, 150, 30);

        jLabel3.setText("Mesa nro:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 100, 70, 30);

        jLabel4.setText("Estado:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 130, 90, 40);
        getContentPane().add(txtMozoOrigen);
        txtMozoOrigen.setBounds(140, 70, 220, 30);
        getContentPane().add(txtMesaNro);
        txtMesaNro.setBounds(90, 90, 90, 50);
        getContentPane().add(txtMesaEstado);
        txtMesaEstado.setBounds(80, 130, 100, 40);

        setBounds(0, 0, 416, 372);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        aceptarTransferencia();
        //Notificar MozoOrigen que transfer fue aceptada
        dispose();        
        //mostrar mesas!!!
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnRechazarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRechazarActionPerformed
        rechazarTransferencia();
        //Notificar MozoOrigen que transfer fue rechazada
        dispose();        
    }//GEN-LAST:event_btnRechazarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnRechazar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel txtMesaEstado;
    private javax.swing.JLabel txtMesaNro;
    private javax.swing.JLabel txtMozoOrigen;
    // End of variables declaration//GEN-END:variables

    private void cargarDatosTransferencia() {
        txtMozoOrigen.setText(controlador.getMozo() + "");
        txtMesaNro.setText(controlador.getMozo().getTransferencia().getMesaATransferir().getNumero() + "");
        if (controlador.getMozo().getTransferencia().getMesaATransferir().getAbierta()) {
            txtMesaEstado.setText("Abierta");
        } else {
            txtMesaEstado.setText("Cerrada");
        }
    }

    private void aceptarTransferencia() {
        controlador.getMozo().transferir();
        System.out.println("Avisar a MozoOrigen que Transferencia fue aceptada");
    }

    private void rechazarTransferencia() {
        System.out.println("Avisar a MozoOrigen que Transferencia fue RECHAZADA");

    }

}
