/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistaMozo;

import controlador.ControladorMozo;
import java.util.ArrayList;
import modelo.Mesa;
import modelo.Mozo;
import modelo.SistemaAtencionCliente;

/**
 *
 * @author Dominique
 */
public class TransferirAMozoJDialog extends javax.swing.JDialog {

    private ControladorMozo controlador;


    /**
     * Creates new form TransferirAMozoJDialog
     */
    public TransferirAMozoJDialog(ControladorMozo pControlador) {
        initComponents();
        setModal(true);
        setLocationRelativeTo(null);
        controlador = pControlador;
        mostrarListaMozosLogueados();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstMozosLogueados = new javax.swing.JList();
        btnTransferencia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Mozos logueados:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 10, 130, 40);

        jScrollPane1.setViewportView(lstMozosLogueados);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 60, 280, 240);

        btnTransferencia.setText("Iniciar transferencia");
        btnTransferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransferenciaActionPerformed(evt);
            }
        });
        getContentPane().add(btnTransferencia);
        btnTransferencia.setBounds(130, 330, 170, 40);

        setBounds(0, 0, 349, 438);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTransferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransferenciaActionPerformed
        // TODO add your handling code here:     
        solicitarTransferencia();
    }//GEN-LAST:event_btnTransferenciaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTransferencia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lstMozosLogueados;
    // End of variables declaration//GEN-END:variables

    private void solicitarTransferencia() {
        Mozo mozoDestino = (Mozo)lstMozosLogueados.getSelectedValue();
        Mozo mozoOrigen = controlador.getMozo();
        Mesa mesaATransferir = controlador.getSeleccionada();
        
        if(mozoDestino!=null){
        mozoOrigen.solicitudTransferencia(mozoDestino, mesaATransferir);
        }else{
            System.out.println("Error, debe seleccionar un mozo destino");
        }      
        dispose();
    }

    private void mostrarListaMozosLogueados() { 
        this.lstMozosLogueados.removeAll();
        ArrayList<Mozo> mozos = controlador.getFachada().getMozosLogueados(controlador.getMozo());     
        this.lstMozosLogueados.setListData(mozos.toArray());
    }
}
